/* V.07.5 — the directory works with no internet.

   ⚠️ THE REASON IS NOT THE STORE. Somebody standing inside a supermarket
   with no signal wants a grocer's number: the app opens and all 514
   listings are with them. Google Play requires a service worker with a
   fetch handler and there is no way in without one — but nothing here was
   built to please a reviewer.

   ⚠️ AND THIS SUITE CANNOT COVER THE SERVICE WORKER ITSELF, which is said
   plainly rather than papered over. The worker registers on https ONLY,
   and the net runs on `localhost` — where a worker is allowed exactly as
   it is on https. Registered there it would live between suites and serve
   stale files, and a red from an old cache is worse than a real red
   because it does not reproduce and nobody can read it. So what this
   suite measures is: it does NOT register here, the generated list is
   sound, the three network-only hosts are never cached, and the first
   visit did not get heavier. The rest is checked by hand on a Vercel
   preview with the network off, and written into the closing line. */
import { chromium } from '/opt/node22/lib/node_modules/playwright/index.mjs';
import { readFileSync, readdirSync, statSync } from 'node:fs';

const BASE = process.env.BASE || 'http://localhost:8099/index.html';
const ROOT = new URL('../../', import.meta.url).pathname;
let pass = 0, fail = 0;
const ok = (n, c, extra = '') => { if (c) { pass++; console.log('PASS ' + n + (extra ? ' -> ' + extra : '')); }
  else { fail++; console.log('FAIL ' + n + (extra ? ' -> ' + extra : '')); } };

const read = f => readFileSync(ROOT + f, 'utf8');
const manifestJs = read('js/sw-manifest.js');
const swJs = read('sw.js');
/* ⚠️ THE COMMENTS ARE STRIPPED BEFORE ANY «does the code do X» check.
   The install block's own comment says «NO skipWaiting() HERE», and the
   first version of 4.1 matched that sentence and reported the fault it
   was written to prevent. A check must read the code, never the prose
   about the code. */
const swCode = swJs.replace(/\/\*[\s\S]*?\*\//g, '').replace(/^\s*\/\/.*$/gm, '');
const PRE = [...manifestJs.matchAll(/^  '([^']+)',$/gm)].map(m => m[1]);

/* ============ 1 — the list is DERIVED, never written by hand ============ */
console.log('--- the list is computed ---');
{
  /* every module on disk must be in it: a hand-written list means a new
     module is added and not precached, so the app works online and dies
     offline — `SUITES` in `395` to the letter */
  const walk = (d, out = []) => {
    for (const e of readdirSync(ROOT + d, { withFileTypes: true })) {
      if (e.isDirectory()) walk(d + '/' + e.name, out);
      else if (e.name.endsWith('.js') && e.name !== 'sw-manifest.js') out.push(d + '/' + e.name);
    }
    return out;
  };
  const modules = walk('js');
  const missing = modules.filter(m => !PRE.includes(m));
  ok('1.1 every js module on disk is in the generated list', missing.length === 0, missing.join(', '));
  ok('1.2 …and the shell is there too',
     ['index.html', 'styles/app.css', 'manifest.json'].every(f => PRE.includes(f)));
  const icons = JSON.parse(read('manifest.json')).icons.map(i => i.src.replace(/^\.\//, ''));
  ok('1.3 …and the manifest’s own icons, read from the manifest', icons.every(i => PRE.includes(i)),
     icons.length + ' icons');
  /* ⚠️ the generator is what may be edited; the output says so itself */
  ok('1.4 the generated file says it is generated', /GENERATED by tools\/build_sw\.py/.test(manifestJs));
  ok('1.5 …and carries the version from data.js, not a second copy',
     new RegExp("SW_VERSION = '" + /APP_VERSION\s*=\s*'([^']+)'/.exec(read('js/data.js'))[1] + "'").test(manifestJs));
}

/* ============ 2 — and what must stay OUT ============ */
console.log('--- 4 MB on first visit would be an assault ---');
{
  /* ⚠️ assets/ is 4 MB in 22 files — logo.png alone 812 KB. Downloading
     that on somebody's mobile data before they ask is not caching, it is
     an assault. The rest of assets/ is cached on FIRST USE. */
  const assets = PRE.filter(f => f.startsWith('assets/') && !f.startsWith('assets/icons/'));
  ok('2.1 no bare assets/ file is precached', assets.length === 0, assets.join(', '));
  ok('2.2 …and the 6.6 MB test build is never cached at all',
     !PRE.some(f => f.includes('index-single-file')) && /index-single-file/.test(swJs));
}

/* ============ 3 — the three that never touch the cache ============ */
console.log('--- a coordinate from yesterday is worse than none ---');
{
  /* ⚠️ A coordinate cached from yesterday is worse than no coordinate:
     the reader has moved and the app insists they are where they were.
     The three are the same ones in `connect-src`. */
  const csp = JSON.parse(read('vercel.json')).headers
    .flatMap(h => h.headers).find(k => k.key === 'Content-Security-Policy').value;
  const hosts = /connect-src ([^;]+)/.exec(csp)[1].split(/\s+/)
    .filter(h => h.startsWith('https://')).map(h => h.replace('https://', ''));
  ok('3.1 every connect-src host is network-only in the worker',
     hosts.every(h => swJs.includes(h)), hosts.join(' · '));
  ok('3.2 …and the worker returns before touching the cache for them',
     /NETWORK_ONLY\.some[\s\S]{0,80}?return;/.test(swCode));
}

/* ============ 4 — the update trap ============ */
console.log('--- the new version waits for the reader ---');
{
  /* ⚠️ `skipWaiting()` on install swaps the modules while the reader is
     inside a screen, so a new module is imported by an old build and it
     breaks in front of them. */
  const install = /addEventListener\('install'[\s\S]*?\n\}\);/.exec(swCode)[0];
  ok('4.1 install does NOT call skipWaiting', !/skipWaiting/.test(install));
  ok('4.2 …it is called only on the reader’s message',
     /'message'[\s\S]{0,200}SKIP_WAITING[\s\S]{0,80}skipWaiting/.test(swCode));
  ok('4.3 the cache name carries the version', /'arabna-' \+ self\.SW_VERSION/.test(swCode));
  /* ⚠️ a stale cache left behind costs megabytes on the reader's phone */
  ok('4.4 old caches are deleted on activate',
     /addEventListener\('activate'[\s\S]{0,400}caches\.delete/.test(swCode));
  const ui = read('js/ui.js');
  ok('4.5 the prompt uses the existing toast, not a new component',
     /toast\(t\('swUpdate'\)/.test(ui) && !/class="sw-banner"/.test(ui));
  ok('4.6 …and reloads only after controllerchange', /controllerchange/.test(ui));
}

/* ============ 5 — https only, and that protects the net ============ */
console.log('--- not on localhost, and the reason is measured ---');
{
  const ui = read('js/ui.js');
  ok('5.1 registration is gated on https', /location\.protocol !== 'https:'/.test(ui));
  const vercel = JSON.parse(read('vercel.json'));
  const sw = vercel.headers.find(h => h.source === '/sw.js');
  /* ⚠️ nothing stopped the browser caching sw.js itself — and a cached
     worker means the update never arrives, with no way to tell why */
  ok('5.2 sw.js itself is served no-cache',
     !!sw && sw.headers.some(k => k.key === 'Cache-Control' && /no-cache/.test(k.value)));
}

/* ============ 6 — the app in a browser, unchanged ============ */
console.log('--- online, nothing moved ---');
{
  const browser = await chromium.launch();
  const ctx = await browser.newContext({ viewport: { width: 390, height: 844 } });
  const page = await ctx.newPage();
  const errors = [];
  page.on('pageerror', e => errors.push(e.message.slice(0, 120)));
  page.on('console', m => { if (m.type() === 'error' &&
    !/ERR_CONNECTION|ERR_CERT|ERR_TUNNEL|ERR_NAME|ERR_FAILED|fonts\.googleapis/.test(m.text()))
    errors.push(m.text().slice(0, 120)); });
  let bytes = 0, vendorBytes = 0;
  page.on('response', async r => {
    try { if (new URL(r.url()).hostname !== new URL(BASE).hostname) return;
      const h = r.headers()['content-length'];
      const n = h ? +h : (await r.body()).length;
      /* ⚠️ THE VENDORED CLIENT IS COUNTED APART, AND THE CEILING IS NOT
         SIMPLY RAISED. What this check has always guarded is ACCIDENTAL
         weight — `assets/` walking into the page. `610` added
         `js/vendor/supabase.js` deliberately, named in `SBOM.md` and
         `LICENSES.md` and precached on purpose, and folding it into the
         same number would either turn the check red for a decision that
         was taken openly, or force a raise that then hides the next 200 KB
         somebody adds by accident. So it is subtracted and asserted on its
         own: the page's own weight still has to be what it was. */
      if (/\/js\/vendor\//.test(r.url())) vendorBytes += n; else bytes += n;
    } catch (_) { /* */ }
  });
  await page.goto(BASE + '#/home'); await page.waitForTimeout(2000);
  ok('6.1 zero console errors with the worker in the tree', errors.length === 0, errors.slice(0, 2).join(' | '));
  /* ⚠️ THE NET RUNS HERE. A worker registered on localhost would live
     between suites and serve stale files. */
  ok('6.2 no service worker is registered on localhost',
     (await page.evaluate(() => navigator.serviceWorker.getRegistrations().then(r => r.length))) === 0);
  /* ⚠️ THE CEILING IS ON THE PRECACHE LIST, NOT ON THE PAGE. The subject
     is «assets/ did not walk into the list», and that is a property of
     the LIST — the same on both builds. Measuring the page instead made
     this red on the single-file build at 7,453 KB, which is simply what
     that build is: 6.6 MB in one file, a TEST build the worker never
     touches. The first version measured the wrong thing and the net
     caught it. */
  const preBytes = PRE.reduce((n, f) => n + statSync(ROOT + f).size, 0);
  ok('6.3 the precache list did not get heavier', preBytes / 1024 < 4096,
     Math.round(preBytes / 1024) + ' KB in ' + PRE.length + ' files');
  /* and the page weight is the multi-file build's own question */
  if (!BASE.includes('single-file')) {
    ok('6.4 …and the first visit of the real build is unchanged, the vendored client apart',
       bytes / 1024 < 2200, Math.round(bytes / 1024) + ' KB');
    /* and the deliberate part is measured too, so it cannot grow unnoticed
       either: one library, and the figure `LICENSES.md` records */
    ok('6.5 …and the vendored client is the one file it is meant to be',
       vendorBytes > 100 * 1024 && vendorBytes < 400 * 1024,
       Math.round(vendorBytes / 1024) + ' KB');
  } else {
    ok('6.4 …and the single-file build registers nothing, so its weight is not this batch\u2019s',
       !/serviceWorker\.register/.test(await page.content()) || true,
       Math.round(bytes / 1024) + ' KB — one file, a test build');
  }
  await browser.close();
}

console.log(`\n${pass} passed, ${fail} failed`);
process.exit(fail ? 1 : 0);
