#!/usr/bin/env python3
"""Generate js/sw-manifest.js — the precache list and the version.

⚠️ THE LIST IS COMPUTED FROM THE FILES, NEVER WRITTEN BY HAND. A
hand-written list means a new module file is added and not precached — so
the app works online and dies offline, and nobody knows until a reader
complains. That is `SUITES` in `395` to the letter, and it is why this
tool exists rather than a literal array in `sw.js`.

⚠️ AND THE VERSION IS READ FROM `js/data.js`, not written here. It goes
into the cache name, so raising APP_VERSION is what invalidates the old
cache — one number, one place, and no second copy to drift.

What goes in: the shell the app cannot start without.
What stays out: `assets/` — 4 MB in 22 files, `logo.png` alone 812 KB —
because downloading that on somebody's mobile data at the first visit is
an assault on the reader. The rest of `assets/` is cached on first use,
not before. And `index-single-file.html` (6.6 MB) is never cached at all:
it is a test build, not a production one.
"""
import json, os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

def rel(p):
    return os.path.relpath(p, ROOT).replace(os.sep, '/')

version = re.search(r"APP_VERSION\s*=\s*'([^']+)'",
                    open(os.path.join(ROOT, 'js/data.js'), encoding='utf-8').read())
if not version:
    sys.exit('*** ABORT: APP_VERSION not found in js/data.js ***')
version = version.group(1)

files = ['index.html', 'styles/app.css', 'manifest.json']

# every module, wherever it sits under js/ — a new screen is picked up by
# being a file, not by somebody remembering to list it
for base, _dirs, names in os.walk(os.path.join(ROOT, 'js')):
    for n in sorted(names):
        if n.endswith('.js') and n != 'sw-manifest.js':
            files.append(rel(os.path.join(base, n)))

# the manifest's own icons, read from the manifest — ⚠️ measured: it lists
# SEVEN, not the six the batch file said. Deriving means the file decides,
# so the number here is whatever the manifest actually declares.
manifest = json.load(open(os.path.join(ROOT, 'manifest.json'), encoding='utf-8'))
for icon in manifest.get('icons', []):
    src = icon['src'].lstrip('./')
    if src not in files:
        files.append(src)

files = sorted(set(files))

missing = [f for f in files if not os.path.exists(os.path.join(ROOT, f))]
if missing:
    sys.exit('*** ABORT: derived a file that does not exist: %s ***' % ', '.join(missing))

# ⚠️ A derivation that fails silently is worse than a hand-written list,
# because it is assumed safe: a pattern matching nothing would emit an
# empty array and produce a «service worker» that caches nothing and is
# taken for one. The floor is WRITTEN, not computed — a threshold derived
# from the thing it guards always agrees with itself. (`395`'s own rule.)
if len(files) < 20:
    sys.exit('*** ABORT: derived only %d file(s) to precache — the walk is wrong ***' % len(files))

total = sum(os.path.getsize(os.path.join(ROOT, f)) for f in files)

out = os.path.join(ROOT, 'js/sw-manifest.js')
with open(out, 'w', encoding='utf-8') as fh:
    fh.write('/* GENERATED by tools/build_sw.py — do not edit by hand.\n'
             '   The list is derived from the files and the version from\n'
             '   js/data.js; editing it here is lost on the next build. */\n')
    # ⚠️ A CLASSIC SCRIPT, NOT AN ES MODULE. `sw.js` reaches it with
    # `importScripts`, which every browser that runs a service worker
    # supports; a module worker (`type: 'module'`) is still uneven across
    # Safari, and an app that will not install on an iPhone is no use to
    # this community.
    fh.write("self.SW_VERSION = '%s';\n" % version)
    fh.write('self.PRECACHE = [\n')
    for f in files:
        fh.write("  '%s',\n" % f)
    fh.write('];\n')

print('sw-manifest: %d files, %d KB, version %s' % (len(files), total // 1024, version))
